WITH RECURSIVE T1 AS(
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM T1
    WHERE HOUR < 23
)
SELECT A.HOUR ,COUNT(B.DATETIME) AS COUNT
FROM `T1` AS A
LEFT JOIN `ANIMAL_OUTS` AS B
ON A.HOUR = HOUR(B.DATETIME)
GROUP BY A.HOUR