SELECT B.FOOD_TYPE, B.REST_ID, B.REST_NAME, B.FAVORITES
FROM (SELECT `FOOD_TYPE`, `REST_ID`, `REST_NAME`, MAX(`FAVORITES`) AS 'FAVORITES'
      FROM `REST_INFO`
      GROUP BY `FOOD_TYPE`) AS A
INNER JOIN `REST_INFO` AS B
ON A.FOOD_TYPE = B.FOOD_TYPE AND B.FAVORITES = A.FAVORITES
ORDER BY B.FOOD_TYPE DESC