SELECT A.CATEGORY, A.PRICE AS 'MAX_PRICE', A.PRODUCT_NAME
FROM `FOOD_PRODUCT` AS A
INNER JOIN (SELECT `PRODUCT_ID`, ROW_NUMBER() OVER (PARTITION BY `CATEGORY` ORDER BY `PRICE` DESC) AS ROW_NUM
FROM `FOOD_PRODUCT`
WHERE `CATEGORY` IN ('과자', '국', '김치', '식용유')) AS B
ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE B.ROW_NUM = 1
ORDER BY MAX_PRICE DESC